3.1PHPMVC/02SymfonyIntro/blog/src/AppBundle/Entity/IEntity.php
<?php
/**
 * Created by PhpStorm.
 * User: dimitar
 * Date: 10.04.17
 * Time: 10:29
 */

namespace AppBundle\Entity;


interface IEntity
{
    public function getSku();
    public function getTitle();
    public function getPrice();
}

3.1PHPMVC/02SymfonyIntro/blog/src/AppBundle/Controller/CartController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Form\OrderFormType;
use AppBundle\Entity\OrderEntity;
use AppBundle\Service\OrderService;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CartController extends Controller {
	/**
	 * @Route("/cart", name="cart")
	 * @Template()
	 */
	public function indexAction() {
		$order_service = $this->get('app.service.order_service');

		if ($order_service->cartIsEmpty()) {
			return $this->redirectToRoute('catalog');
		}

		$order_form_factory = $this->get('app.factory.form_factory');
		$form = $order_form_factory->createAndHandle('order', OrderFormType::class, new OrderEntity());

		if ($form->isSubmitted() && !$form->isValid()) {
			$this->addFlash('danger', 'Zkontrolujte, prosím, zadané údaje.');
		}

		if (!$form->isSubmitted() || !$form->isValid()) {
			return ['form' => $form->createView()];
		}

		$result = $order_service->finishOrderViaTheForm($form);

		if ($result === OrderService::STATUS_OK) {
			$this->addFlash('success', 'Objednávka byla odeslána. Děkujeme!');

			return $this->redirectToRoute('catalog');
		}

		if ($result === OrderService::STATUS_ERROR) {
			$this->addFlash('danger', 'Objednávku se nepodařilo odeslat. Zkontrolujte, prosím, zadané údaje.');
		}

		return ['form' => $form->createView()];
	}

	/**
	 * @Route("/cart/{sku}/{size}/remove", name="remove_from_cart")
	 * @param $sku
	 * @param $size
	 * @return \Symfony\Component\HttpFoundation\RedirectResponse
	 */
	public function removeFromCartAction($sku, $size) {
		$this->addFlash('success', 'Produkt byl odebrán z košíku.');
		$this->get('app.service.order_service')->removeFromCart($sku, $size);

		return $this->redirectToRoute('cart');
	}
}

3.1PHPMVC/02SymfonyIntro/blog/src/AppBundle/Resources/views/Cart/email.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
  </head>
  <body>
    <strong>Děkujeme Vám za objednávku!</strong><br>
    <br>
    Souhrn objednávky:<br>
    <strong>Jméno a příjmení:</strong> {{ name }}<br>
    <strong>Email:</strong> {{ email }}<br>
    <strong>Poznámka:</strong> <pre>{{ note }}</pre><br>
    <br>
    <table style="border-collapse: collapse;">
      <thead>
        <tr>
          <th style="border-bottom: 1px solid #ccc">Název</th>
          <th style="border-bottom: 1px solid #ccc">Velikost</th>
          <th style="border-bottom: 1px solid #ccc">Cena</th>
        </tr>
      </thead>
      <tbody>
        {% for sku, item in cart.items %}
          {% for size_key, size in item.sizes %}
            <tr>
              <td style="padding: 5px; border-bottom: 1px solid #ccc">{{ item.title }}</td>
              <td style="padding: 5px; border-bottom: 1px solid #ccc">{{ size.title }}</td>
              <td style="padding: 5px; border-bottom: 1px solid #ccc">{{ size.quantity }} * {{ item.price }} Kč = <strong>{{ item.price * size.quantity }} Kč</strong></td>
            </tr>
          {% endfor %}
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td style="padding: 5px; border-bottom: 1px solid #ccc;" colspan="4">&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td style="padding: 5px"><strong>Celkem</strong></td>
          <td style="padding: 5px"><strong>{{ cart.total }} Kč</strong></td>
        </tr>
      </tfoot>
    </table>
    <br>
    <br>
    <strong>Tričko Vám bude předáno na dalším Symfony srazu kde zároveň dojde i k platbě v hotovosti. :)</strong>
    <br>
    <br>
    S pozdravem<br>
    Symfony.cz Team
  </body>
</html>

3.1PHPMVC/02SymfonyIntro/blog/src/AppBundle/Resources/views/Cart/emailAdmin.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
  </head>
  <body>
    <strong>Nová objednávka!</strong><br>
    <br>
    Souhrn objednávky:<br>
    <strong>Jméno a příjmení:</strong> {{ name }}<br>
    <strong>Email:</strong> {{ email }}<br>
    <strong>Poznámka:</strong>
    <pre>{{ note }}</pre>
    <br>
    <br>
    <table style="border-collapse: collapse;">
      <thead>
        <tr>
          <th style="border-bottom: 1px solid #ccc">Název</th>
          <th style="border-bottom: 1px solid #ccc">Velikost</th>
          <th style="border-bottom: 1px solid #ccc">Cena</th>
        </tr>
      </thead>
      <tbody>
        {% for sku, item in cart.items %}
          {% for size_key, size in item.sizes %}
            <tr>
              <td style="padding: 5px; border-bottom: 1px solid #ccc">{{ item.title }}</td>
              <td style="padding: 5px; border-bottom: 1px solid #ccc">{{ size.title }}</td>
              <td style="padding: 5px; border-bottom: 1px solid #ccc">{{ size.quantity }} * {{ item.price }} Kč = <strong>{{ item.price * size.quantity }} Kč</strong></td>
            </tr>
          {% endfor %}
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td style="padding: 5px; border-bottom: 1px solid #ccc;" colspan="4">&nbsp;</td>
        </tr>
        <tr>
          <td></td>
          <td style="padding: 5px"><strong>Celkem</strong></td>
          <td style="padding: 5px"><strong>{{ cart.total }} Kč</strong></td>
        </tr>
      </tfoot>
    </table>
  </body>
</html>

3.1PHPMVC/02SymfonyIntro/blog/src/AppBundle/Resources/views/Cart/index.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% set title = 'Košík' %}

{% block body %}
  <div class="row">
    <div class="col-xs-12">
      <h2 id="cart-section">{{ title }}</h2>

      <div id="cart">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Název</th>
              <th>Velikost</th>
              <th>Cena</th>
              <th>Smazat</th>
            </tr>
          </thead>
          <tbody>
            {% for sku, item in app.session.get('cart').items %}
              {% for size_key, size in item.sizes %}
                <tr>
                  <td>{{ item.title }}</td>
                  <td>{{ size.title }}</td>
                  <td>{{ size.quantity }} * {{ item.price }} Kč = <strong>{{ item.price * size.quantity }} Kč</strong></td>
                  <td><a href="{{ path('remove_from_cart', {'size': size_key, 'sku': sku}) }}"><span class="glyphicon glyphicon-remove text-danger"></span></a></td>
                </tr>
              {% endfor %}
            {% endfor %}
          </tbody>
          <tfoot>
            <tr>
              <td colspan="4" id="cart-delimiter"></td>
            </tr>
            <tr>
              <td></td>
              <td><strong>Celkem</strong></td>
              <td colspan="2"><strong>{{ app.session.get('cart').total }} Kč</strong></td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
      <a href="{{ path('catalog') }}" class="btn btn-primary" role="button">Zpět na produkty</a>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <br>
      <div class="well">Tričko Vám bude předáno na dalším Symfony srazu kde zároveň dojde i k platbě v hotovosti. :)</div>

      {{ form(form) }}
    </div>
  </div>
{% endblock %}